name: Vales+
favicon: null
layout_spectrum: 0.38147
typography_spectrum: 0.76203
title: Vales+
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#454545'
    - '#ffffff'
    - '#060201'
    - '#57bfd6'
    - '#b9b6b3'
  brandStrength: 1
  lightness: 0.7606898124795407
  saturation: 0.3347784949000925
  rhythmicContrast: 0.25359068368561566
purpose: []
