name: Vales+
favicon: null
layout_spectrum: 0.9276449920143932
typography_spectrum: 0.6535177065525204
title: Vales+
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9218363410327584
  lightness: 0.7606898124795407
  saturation: 0.3347784949000925
  rhythmicContrast: 0.25359068368561566
purpose: []
